name: Update data
on:
  schedule:
    - cron:  '0 5 1 * *'
  workflow_dispatch:

jobs:
  ukcat:
    name: Update UK-CAT categories
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fetch latest charity data
      run: |
        python -m ukcat fetch charities
    - name: Apply UK-CAT categories
      run: |
        python -m ukcat apply ukcat --charity-csv "./data/charities_active.csv" -f "name" -f "activities"
        python -m ukcat apply ukcat --charity-csv "./data/charities_inactive.csv" -f "name" -f "objects"
    - name: Update UKCAT docs
      run: |
        python -m ukcat docs ukcat
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update by GitHub Action" -a)
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # CUSTOM_DOMAIN: optionaldomain.com
        CONFIG_FILE: ./mkdocs.yml
        REQUIREMENTS: ./mkdocs-requirements.txt
        # EXTRA_PACKAGES: build-base
        # GITHUB_DOMAIN: github.myenterprise.com
  icnptso:
    name: Update ICNPTSO categories
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fetch latest charity data
      run: |
        python -m ukcat fetch charities
    - name: Apply ICNPTSO model
      run: |
        python -m ukcat apply icnptso --charity-csv "./data/charities_active.csv" -f "name" -f "activities"
        python -m ukcat apply icnptso --charity-csv "./data/charities_inactive.csv" -f "name" -f "objects"
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update by GitHub Action" -a)
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
